export const DeviseLists = [
    { pays: "Afghanistan", monnaie: "Afghani", devise: "AFN", code: "AF" },
    { pays: "Afrique du Sud", monnaie: "Rand", devise: "ZAR", code: "ZA" },
    { pays: "Albanie", monnaie: "Lek", devise: "ALL", code: "AL" },
    { pays: "Algérie", monnaie: "Dinar algérien", devise: "DZD", code: "DZ" },
    { pays: "Allemagne", monnaie: "Euro", devise: "EUR", code: "DE" },
    { pays: "Andorre", monnaie: "Euro", devise: "EUR", code: "AD" },
    { pays: "Angola", monnaie: "Kwanza", devise: "AOA", code: "AO" },
    { pays: "Anguilla", monnaie: "Dollar des Caraïbes orientales", devise: "XCD", code: "AI" },
    { pays: "Antigua-et-Barbuda", monnaie: "Dollar des Caraïbes orientales", devise: "XCD", code: "AG" },
    { pays: "Antilles Néerlandaises", monnaie: "Florin des Antilles", devise: "ANG", code: "AN" },
    { pays: "Arabie Saoudite", monnaie: "Riyal saoudien", devise: "SAR", code: "SA" },
    { pays: "Argentine", monnaie: "Peso argentin", devise: "ARS", code: "AR" },
    { pays: "Arménie", monnaie: "Dram arménien", devise: "AMD", code: "AM" },
    { pays: "Aruba", monnaie: "Florin d'Aruba", devise: "AWG", code: "AW" },
    { pays: "Australie", monnaie: "Dollar australien", devise: "AUD", code: "AU" },
    { pays: "Autriche", monnaie: "Euro", devise: "EUR", code: "AT" },
    { pays: "Azerbaïdjan", monnaie: "Manat", devise: "AZN", code: "AZ" },
    { pays: "Bahamas", monnaie: "Dollar des Bahamas", devise: "BSD", code: "BS" },
    { pays: "Bahreïn", monnaie: "Dinar de Bahreïn", devise: "BHD", code: "BH" },
    { pays: "Bangladesh", monnaie: "Taka", devise: "BDT", code: "BD" },
    { pays: "Barbade", monnaie: "Dollar de Barbade", devise: "BBD", code: "BB" },
    { pays: "Bélarus", monnaie: "Rouble bélorusse", devise: "BYR", code: "BY" },
    { pays: "Belgique", monnaie: "Euro", devise: "EUR", code: "BE" },
    { pays: "Belize", monnaie: "Dollar de Belize", devise: "BZD", code: "BZ" },
    { pays: "Bénin", monnaie: "Franc CFA - BCEAO †", devise: "XOF", code: "BJ" },
    { pays: "Bermudes", monnaie: "Dollar des Bermudes", devise: "BMD", code: "BM" },
    { pays: "Bhoutan", monnaie: "Rhoupie indienne", devise: "INR", code: "BT" },
    { pays: "Bolivie", monnaie: "Boliviano", devise: "BOB", code: "BO" },
    { pays: "Bosnie-Herzégovine", monnaie: "Mark convertible", devise: "BAM", code: "BA" },
    { pays: "Botswana", monnaie: "Pula", devise: "BWP", code: "BW" },
    { pays: "Bouvet, Île", monnaie: "Couronne norvégienne", devise: "NOK", code: "BV" },
    { pays: "Brésil", monnaie: "Real", devise: "BRL", code: "BR" },
    { pays: "Brunei Darussalam", monnaie: "Dollar de Brunei", devise: "BND", code: "BN" },
    { pays: "Bulgarie", monnaie: "Bulgarian Lev", devise: "BGN", code: "BG" },
    { pays: "Burkina Faso", monnaie: "Franc CFA - BCEAO †", devise: "XOF", code: "BF" },
    { pays: "Burundi", monnaie: "Franc du Burundi", devise: "BIF", code: "BI" },
    { pays: "Caïmans, Îles", monnaie: "Dollar des Iles Caïmans", devise: "KYD", code: "KY" },
    { pays: "Cambodge", monnaie: "Riel", devise: "KHR", code: "KH" },
    { pays: "Cameroun", monnaie: "Franc CFA - BEAC ‡", devise: "XAF", code: "CM" },
    { pays: "Canada", monnaie: "Dollar canadien", devise: "CAD", code: "CA" },
    { pays: "Cap-Vert", monnaie: "Escudo du Cap-Vert", devise: "CV", code: "CV" },
    { pays: "Centrafricaine, République", monnaie: "Franc CFA - BEAC ‡", devise: "XAF", code: "CF" },
    { pays: "Chili", monnaie: "Peso chilien", devise: "CLP", code: "CL" },
    { pays: "Chine", monnaie: "Yuan Ren-Min-Bi", devise: "CNY", code: "CN" },
    { pays: "Christmas, Île", monnaie: "Dollar australien", devise: "AUD", code: "CX" },
    { pays: "Chypre", monnaie: "Livre cypriote", devise: "CYP", code: "CY" },
    { pays: "Cocos (Keeling), Îles", monnaie: "Dollar australien", devise: "AUD", code: "CC" },
    { pays: "Colombie", monnaie: "Peso colombien", devise: "COP", code: "CO" },
    { pays: "Comores", monnaie: "Franc des Comores", devise: "KMF", code: "KM" },
    { pays: "Congo", monnaie: "Franc CFA - BEAC", devise: "XAF", code: "CG" },
    { pays: "Congo, La République démocratique du", monnaie: "Franc Congolais", devise: "CDF", code: "CD" },
    { pays: "Cook, Îles", monnaie: "Dollar néo-zélandais", devise: "NZD", code: "CK" },
    { pays: "Corée, République de", monnaie: "Won", devise: "KRW", code: "KR" },
    { pays: "Corée, République Populaire démocratique de", monnaie: "Won de la Corée du Nord", devise: "KPW", code: "KP" },
    { pays: "Costa Rica", monnaie: "Colon de Costa Rica", devise: "CRC", code: "CR" },
    { pays: "Côte D'ivoire", monnaie: "Franc CFA - BCEAO", devise: "XOF", code: "CI" },
    { pays: "Croatie", monnaie: "Kuna", devise: "HRK", code: "HR" },
    { pays: "Cuba", monnaie: "Peso cubain", devise: "CUP", code: "CU" },
    { pays: "Danemark", monnaie: "Couronne danoise", devise: "DKK", code: "DK" },
    { pays: "Djibouti", monnaie: "Franc de Djibouti", devise: "DJF", code: "DJ" },
    { pays: "Dominicaine, République", monnaie: "Peso dominicain", devise: "DOP", code: "DO" },
    { pays: "Dominique", monnaie: "Dollar des Caraïbes orientales", devise: "XCD", code: "DM" },
    { pays: "Égypte", monnaie: "Livre égyptienne", devise: "EGP", code: "EG" },
    { pays: "El Savador", monnaie: "Colon du El Salvador", devise: "SVC", code: "SV" },
    { pays: "Émirats Arabes Unis", monnaie: "Dirham des émirats arabes unis", devise: "AED", code: "AE" },
    { pays: "Équateur", monnaie: "Dollar des États-Unis", devise: "USD", code: "EC" },
    { pays: "Érythrée", monnaie: "Nakfa", devise: "ERN", code: "ER" },
    { pays: "Espagne", monnaie: "Euro", devise: "EUR", code: "ES" },
    { pays: "Estonie", monnaie: "Couronne estonienne", devise: "EEK", code: "EE" },
    { pays: "Etats-Unis", monnaie: "Dollar des Etats-Unis", devise: "USD", code: "US" },
    { pays: "Éthiopie", monnaie: "Birr éthiopien", devise: "ETB", code: "ET" },
    { pays: "Falkland, Îles (Malvinas)", monnaie: "Livre de Falkland", devise: "FKP", code: "FK" },
    { pays: "Féroé, Îles", monnaie: "Couronne danoise", devise: "DKK", code: "FO" },
    { pays: "Fidji", monnaie: "Dollar de Fidji", devise: "FJD", code: "FJ" },
    { pays: "Finlande", monnaie: "Euro", devise: "EUR", code: "FI" },
    { pays: "France", monnaie: "Euro", devise: "EUR", code: "FR" },
    { pays: "Gabon", monnaie: "Franc CFA - BEAC  ", devise: "XAF", code: "GA" },
    { pays: "Gambie", monnaie: "Dalasi", devise: "GMD", code: "GM" },
    { pays: "Géorgie", monnaie: "Lari", devise: "GEL", code: "GE" },
    { pays: "Géorgie du Sud et Îles Sandwich du Sud", monnaie: "Lari", devise: "GEL", code: "GS" },
    { pays: "Ghana", monnaie: "Ghana Cedi", devise: "GHS", code: "GH" },
    { pays: "Gibraltar", monnaie: "Livre de Gibraltar", devise: "GIP", code: "GI" },
    { pays: "Grèce", monnaie: "Euro", devise: "EUR", code: "GR" },
    { pays: "Grenade", monnaie: "Dollar des Caraïbes orientales", devise: "USD", code: "GD" },
    { pays: "Guatemala", monnaie: "Quetzal", devise: "GTQ", code: "GT" },
    { pays: "Guinée", monnaie: "Franc guinéen", devise: "GNF", code: "GN" },
    { pays: "Guinée-Bissau", monnaie: "Peso de Guinée-Bissau", devise: "GWP", code: "GW" },
    { pays: "Guinée Équatoriale", monnaie: "Franc CFA - BEAC", devise: "XAF", code: "GQ" },
    { pays: "Guyane", monnaie: "Dollar de Guyane ", devise: "GYD", code: "GY" },
    { pays: "Guyane Française", monnaie: "Euro", devise: "EUR", code: "GF" },
    { pays: "Haïti", monnaie: "Gourde", devise: "HTG", code: "HT" },
    { pays: "Heard et Îles Mcdonald, Île", monnaie: "Dollar australien", devise: "AUD", code: "HM" },
    { pays: "Honduras", monnaie: "Lempira", devise: "HNL", code: "HN" },
    { pays: "Hong-Kong", monnaie: "Dollar de Hong-Kong", devise: "HKD", code: "HK" },
    { pays: "Hongrie", monnaie: "Forint", devise: "HUF", code: "HU" },
    { pays: "Îles mineures éloignées des États-Unis", monnaie: "Dollar des États-Unis", devise: "USD", code: "UM" },
    { pays: "Îles Vierges (Britanniques)", monnaie: "Dollar des États-Unis", devise: "USD", code: "VG" },
    { pays: "Îles Vierges (É.-U.)", monnaie: "Dollar des États-Unis", devise: "USD", code: "VI" },
    { pays: "Inde", monnaie: "Roupie indienne", devise: "INR", code: "IN" },
    { pays: "Indonésie", monnaie: "Rupiah", devise: "IDR", code: "ID" },
    { pays: "Iran (République Islamique d')", monnaie: "Rial iranien", devise: "IRR", code: "IR" },
    { pays: "Iraq", monnaie: "Dinar iraquien", devise: "IQD", code: "IQ" },
    { pays: "Irlande", monnaie: "Euro", devise: "EUR", code: "IE" },
    { pays: "Islande", monnaie: "Couronne islandaise", devise: "ISK", code: "IS" },
    { pays: "Israël", monnaie: "Nouveau israëli sheqel", devise: "ILS", code: "IL" },
    { pays: "Italie", monnaie: "Euro", devise: "EUR", code: "IT" },
    { pays: "Jamaïque", monnaie: "Dollar jamaïcain", devise: "JMD", code: "JM" },
    { pays: "Japon", monnaie: "Yen", devise: "JPY", code: "JP" },
    { pays: "Jordanie", monnaie: "Dinar jordanien", devise: "JOD", code: "JO" },
    { pays: "Kazakhstan", monnaie: "Tenge", devise: "KZT", code: "KZ" },
    { pays: "Kenya", monnaie: "Shilling du Kenya", devise: "KES", code: "KE" },
    { pays: "Kirghizistan", monnaie: "Som", devise: "KGS", code: "KG" },
    { pays: "Kiribati", monnaie: "Dollar australien", devise: "AUD", code: "KI" },
    { pays: "Koweït", monnaie: "Dinar koweïtien", devise: "KWD", code: "KW" },
    { pays: "Lao, République Démocratique populaire", monnaie: "Kip", devise: "LAK", code: "LA" },
    { pays: "Lesotho", monnaie: "Rans", devise: "ZAR", code: "LS" },
    { pays: "Lettonie", monnaie: "Lats letton", devise: "LVL", code: "LV" },
    { pays: "Liban", monnaie: "Livre libanaise", devise: "LBP", code: "LB" },
    { pays: "Libéria", monnaie: "Dollar libérien", devise: "LRD", code: "LR" },
    { pays: "Libyenne, Jamahiriya Arabe", monnaie: "Dinar libyen", devise: "LYD", code: "LY" },
    { pays: "Liechtenstein", monnaie: "Franc suisse", devise: "CHF", code: "LI" },
    { pays: "Lituanie", monnaie: "Litas lituanien", devise: "LTL", code: "LT" },
    { pays: "Luxembourg", monnaie: "Euro", devise: "EUR", code: "LU" },
    { pays: "Macao", monnaie: "Pataca", devise: "MOP", code: "MO" },
    { pays: "Macédoine, ancienne République Yougoslave de", monnaie: "Denar", devise: "MKD", code: "MK" },
    { pays: "Madagascar", monnaie: "Malagasy Ariary", devise: "MGA", code: "MG" },
    { pays: "Malaisie", monnaie: "Ringgit de Malaisie", devise: "MYR", code: "MY" },
    { pays: "Malawi", monnaie: "Kwacha", devise: "MWK", code: "MW" },
    { pays: "Maldives", monnaie: "Rufiyaa", devise: "MVR", code: "MV" },
    { pays: "Mali", monnaie: "Franc CFA - BCEAO", devise: "XOF", code: "ML" },
    { pays: "Malte", monnaie: "Livre maltaise", devise: "MTL", code: "MT" },
    { pays: "Mariannes du Nord, Îles", monnaie: "Dollar des Etats-Unis", devise: "USD", code: "MP" },
    { pays: "Maroc", monnaie: "Dirham marocain", devise: "MAD", code: "MA" },
    { pays: "Marshall, Îles", monnaie: "Dollar des États-Unis", devise: "USD", code: "MH" },
    { pays: "Martinique", monnaie: "Euro", devise: "EUR", code: "MQ" },
    { pays: "Maurice", monnaie: "Roupie de Maurice", devise: "MUR", code: "MU" },
    { pays: "Mauritanie", monnaie: "Ouguija", devise: "MRO", code: "MR" },
    { pays: "Mayotte", monnaie: "Euro", devise: "EUR", code: "YT" },
    { pays: "Mexique", monnaie: "Peso mexicain", devise: "MXN", code: "MX" },
    { pays: "Moldova, République de", monnaie: "Leu de Moldavie", devise: "MDL", code: "MD" },
    { pays: "Monaco", monnaie: "Euro", devise: "EUR", code: "MC" },
    { pays: "Mongolie", monnaie: "Tugrik", devise: "MNT", code: "MN" },
    { pays: "Monténégro", monnaie: "Euro", devise: "EUR", code: "ME" },
    { pays: "Montserrat", monnaie: "Dollar des Caraïbes orientales", devise: "XCD", code: "MS" },
    { pays: "Mozambique", monnaie: "Metical", devise: "MZN", code: "MZ" },
    { pays: "Myanmar", monnaie: "Kyat", devise: "MM", code: "MM" },
    { pays: "Namibie", monnaie: "Rand", devise: "ZAR", code: "NA" },
    { pays: "Nauru", monnaie: "Dollar australien", devise: "AUD", code: "NR" },
    { pays: "Népal", monnaie: "Roupie du Népal", devise: "NPR", code: "NP" },
    { pays: "Nicaragua", monnaie: "Cordoba Oro", devise: "NIO", code: "NI" },
    { pays: "Niger", monnaie: "Franc CFA - BCEAO", devise: "XOF", code: "NE" },
    { pays: "Nigeria", monnaie: "Naira", devise: "NGN", code: "NG" },
    { pays: "Niué", monnaie: "Dollar néo-zélandais", devise: "NZD", code: "NU" },
    { pays: "Norfolk, Île", monnaie: "Dollar australien", devise: "AUD", code: "NF" },
    { pays: "Norvège", monnaie: "Couronne norvégienne", devise: "NOK", code: "NO" },
    { pays: "Nouvelle-Calédonie", monnaie: "Franc CFP", devise: "XPF", code: "NC" },
    { pays: "Nouvelle-Zélande", monnaie: "Dollar néo-zélandais", devise: "NZD", code: "NZ" },
    { pays: "Océan Indien, Territoire Britannique de l'", monnaie: "Dollar des États-Unis", devise: "USD", code: "IO" },
    { pays: "Oman", monnaie: "Rial Omani", devise: "OMR", code: "OM" },
    { pays: "Ouganda", monnaie: "Shilling ougandais", devise: "UGX", code: "UG" },
    { pays: "Ouzbékistan", monnaie: "Soum d'Ouzbékistan", devise: "UZS", code: "UZ" },
    { pays: "Pakistan", monnaie: "Roupie du Pakistan", devise: "PKR", code: "PK" },
    { pays: "Palaos", monnaie: "Dollar des États-Unis", devise: "USD", code: "PW" },
    { pays: "Panama", monnaie: "Balboa", devise: "PAB", code: "PA" },
    { pays: "Papouasie-Nouvelle-Guinée", monnaie: "Kina", devise: "PGK", code: "PG" },
    { pays: "Paraguay", monnaie: "Guarani", devise: "PYG", code: "PY" },
    { pays: "Pays-Bas", monnaie: "Euro", devise: "EUR", code: "NL" },
    { pays: "Pérou", monnaie: "Nouveau Sol", devise: "PEN", code: "PE" },
    { pays: "Philippines", monnaie: "Afghani", devise: "Peso philippin", code: "PH" },
    { pays: "Pitcairn", monnaie: "Dollar néo-zélandais", devise: "NZD", code: "PN" },
    { pays: "Pologne", monnaie: "Zloty", devise: "PLN", code: "PL" },
    { pays: "Polynésie Française", monnaie: "Franc CFP", devise: "XPF", code: "PF" },
    { pays: "Porto Rico", monnaie: "Dollar des États-Unis", devise: "USD", code: "PR" },
    { pays: "Portugal", monnaie: "Euro", devise: "EUR", code: "PT" },
    { pays: "Qatar", monnaie: "Riyal du Qatar", devise: "QAR", code: "QA" },
    { pays: "Réunion", monnaie: "Euro", devise: "EUR", code: "RE" },
    { pays: "Roumanie", monnaie: "Leu Roumain", devise: "RON", code: "RO" },
    { pays: "Royaume-Uni", monnaie: "Livre sterling", devise: "GBP", code: "GB" },
    { pays: "Russie, Fédération De", monnaie: "Rouble russe", devise: "RUB", code: "RU" },
    { pays: "Rwanda", monnaie: "Franc du Rwanda", devise: "RWF", code: "RW" },
    { pays: "Sahara Occidental", monnaie: "Dirham marocain", devise: "MAD", code: "EH" },
    { pays: "Sainte-Hélène", monnaie: "Livre de Sainte-Hélène", devise: "SHP", code: "SH" },
    { pays: "Saint-Kitts-et-Nevis", monnaie: "Dollar des Caraïbes orientales", devise: "XCD", code: "KN" },
    { pays: "Sainte-Lucie", monnaie: "Dollar des Caraïbes orientales", devise: "XCD", code: "LC" },
    { pays: "Saint-Marin", monnaie: "Euro", devise: "EUR", code: "SM" },
    { pays: "Saint Pierre et Miquelon", monnaie: "Euro", devise: "EUR", code: "PM" },
    { pays: "Saint-Vincent-et-Grenadines", monnaie: "Dollar des Caraïbes orientales", devise: "XCD", code: "VC" },
    { pays: "Salomon, Îles", monnaie: "Dollar de Salomon", devise: "SBD", code: "SB" },
    { pays: "Samoa", monnaie: "Tala", devise: "WST", code: "WS" },
    { pays: "Samoa Américaines", monnaie: "Dollar des États-Unis", devise: "USD", code: "AS" },
    { pays: "São Tomé-et-Principe", monnaie: "Dobra", devise: "STD", code: "ST" },
    { pays: "Sénégal", monnaie: "Franc CFA - BCEAO †", devise: "XOF", code: "SN" },
    { pays: "Serbie", monnaie: "Dinar serbe", devise: "RSD", code: "RS" },
    { pays: "Seychelles", monnaie: "Roupie des Seychelles", devise: "SCR", code: "SC" },
    { pays: "Sierra Leone", monnaie: "Leone", devise: "SLL", code: "SL" },
    { pays: "Singapour", monnaie: "Dollar de Singapour", devise: "SGD", code: "SG" },
    { pays: "Slovaquie", monnaie: "Couronne slovaque", devise: "SKK", code: "SK" },
    { pays: "Slovénie", monnaie: "Euro", devise: "EUR", code: "SI" },
    { pays: "Somalie", monnaie: "Shilling de Somalie", devise: "SOS", code: "SO" },
    { pays: "Soudan", monnaie: "Livre soudanaise", devise: "SDG", code: "SD" },
    { pays: "Sri Lanka", monnaie: "Roupie de Sri Lanka", devise: "LKR", code: "LK" },
    { pays: "Suède", monnaie: "Couronne suédoise", devise: "SEK", code: "SE" },
    { pays: "Suisse", monnaie: "Franc Suisse", devise: "CHF", code: "CH" },
    { pays: "Suriname", monnaie: "Dollar de Surinam", devise: "SRD", code: "SR" },
    { pays: "Svalbard et Îles Jan Mayen", monnaie: "Couronne norvégienne", devise: "NOK", code: "SJ" },
    { pays: "Swaziland", monnaie: "Lilangeni", devise: "SZL", code: "SZ" },
    { pays: "Syrienne, République Arabe", monnaie: "Livre syrienne", devise: "SYP", code: "SY" },
    { pays: "Tadjikistan", monnaie: "Somoni", devise: "TJS", code: "TJ" },
    { pays: "Taïwan, Province Chinoise De", monnaie: "Nouveau dollar de Taïwan", devise: "TWD", code: "TW" },
    { pays: "Tanzanie, République-Unie de", monnaie: "Shilling de Tanzanie", devise: "TZS", code: "TZ" },
    { pays: "Terres Australes Françaises", monnaie: "Euro", devise: "EUR", code: "TF" },
    { pays: "Tchad", monnaie: "Franc CFA - BCEAO †", devise: "XAF", code: "TD" },
    { pays: "Tchèque, République", monnaie: "Couronne tchèque", devise: "CZK", code: "CZ" },
    { pays: "Thaïlande", monnaie: "Baht", devise: "THB", code: "TH" },
    { pays: "Timor-Leste", monnaie: "Dollar des États-Unis", devise: "USD", code: "TL" },
    { pays: "Togo", monnaie: "Franc CFA - BCEAO †", devise: "XOF", code: "TG" },
    { pays: "Tokélaou", monnaie: "Dollar néo-zélandais", devise: "NZD", code: "TK" },
    { pays: "Tonga", monnaie: "Pa'anga", devise: "TOP", code: "TO" },
    { pays: "Trinité-Et-Tobago", monnaie: "Dollar de la Trinité et de Tobago", devise: "TTD", code: "TT" },
    { pays: "Tunisie", monnaie: "Dinar tunisien", devise: "TND", code: "TN" },
    { pays: "Turkménistan", monnaie: "Manat", devise: "TMM", code: "TM" },
    { pays: "Turks Et Caïcos, Îles", monnaie: "Dollar des États-Unis", devise: "USD", code: "TC" },
    { pays: "Turquie", monnaie: "Livre turque", devise: "TRY", code: "TR" },
    { pays: "Tuvalu", monnaie: "Dollar australien", devise: "AUD", code: "TV" },
    { pays: "Ukraine", monnaie: "Hryvnia", devise: "UAH", code: "UA" },
    { pays: "Uruguay", monnaie: "Peso uruguayen", devise: "UYU", code: "UY" },
    { pays: "Vanuatu", monnaie: "Vatu", devise: "VUV", code: "VU" },
    { pays: "Vatican, État de la Cité Du(Saint-Siège)", monnaie: "Euro", devise: "EUR", code: "VA" },
    { pays: "Venezuela", monnaie: "Bolivar Fuerte", devise: "VEF", code: "VE" },
    { pays: "Viet Nam", monnaie: "Dong", devise: "VND", code: "VN" },
    { pays: "Wallis et Futuna", monnaie: "Franc CFP", devise: "XPF", code: "WF" },
    { pays: "Yémen", monnaie: "Riyal du Yémen", devise: "YER", code: "YE" },
    { pays: "Zambie", monnaie: "Kwacha", devise: "KMW", code: "ZM" },
    { pays: "Zimbabwe", monnaie: "Dollar du Zimbabwe", devise: "ZWD", code: "ZW" },
  ];
  