import { GET_ENTERPRISE_BY_USER_ID,GET_ENTERPRISE_INFO,MUTATE_UPDATE_AGENCY } from './enterprise';
import {  MUTATE_INSERT_USERS,MUTATE_INSERT_USERS_AND_ENTERPRISE } from "./register";
import {MUTATE_LOGIN} from './login'
import { GET_USER_ID,GET_USER_INFO, MUTATE_UPDATE_USERS,MUTATE_UPDATE_AUTH_PASSWORD,MUTATE_DELETE } from './user';
import {MUTATE_INSERT_CONFIGURATION,GET_CONFIGURATION_INFO} from './configuration'
import {MUTATE_INSERT_AGENT,GET_AGENTS} from './Agent'
export {
    MUTATE_INSERT_USERS,
    MUTATE_LOGIN,
    MUTATE_INSERT_USERS_AND_ENTERPRISE,
    GET_ENTERPRISE_BY_USER_ID,
    GET_USER_ID,
    GET_ENTERPRISE_INFO,
    GET_USER_INFO,
    MUTATE_UPDATE_USERS,
    MUTATE_UPDATE_AGENCY,
    MUTATE_UPDATE_AUTH_PASSWORD,
    MUTATE_INSERT_CONFIGURATION,
    GET_CONFIGURATION_INFO,
    MUTATE_INSERT_AGENT,
    GET_AGENTS,
    MUTATE_DELETE
};